### PR TITLE
Adding a job

### PR DESCRIPTION
**Pull request by A-N-Other**

### CODE REVIEW

**Comment by vsoch** [comment]
We had some trouble with sync-ing this manual approach with our sheet, so we are going to ask you to please use the form instead. https://hpc.social/jobs/about/ Thanks!

**Comment by A-N-Other** [comment]
@vsoch Sure, I've done that. I submitted this job via the form last Thursday, but nothing's appeared, so I'd figured the form wasn't working properly...

**Comment by vsoch** [comment]
Is it possible that you didn't click submit? I don't see it there. Could you try again? And check your browser console for any errors?

**Comment by A-N-Other** [comment]
I've just done it again (again). All three times I've had the success message:
```
hpc.social says
Form Submitted. Thanks.
```

**Comment by vsoch** [comment]
hmm I don't see it - let me test it out.

**Comment by vsoch** [comment]
I have a feeling you are blocking something in your browser (or some other issue) because it worked for me:

image

Are you absolutely sure there isn't an error message in your browser console? Right click -> Inspect -> Console? In the future, perhaps try the form directly:

https://forms.gle/JQVsr3sVzsWhmtvz5

Sorry for the trouble! It should show up for the next round now that I added it.

**Comment by A-N-Other** [comment]
Ah the link there gave me a clue ... our firewall swallows Google drive, Box, Dropbox and everything else, so it's likely that. Thanks for doing it for me - sorry about that!

**Pull request closed without merging**
