### PR TITLE
Update Sheffield job advert.

### PR DESCRIPTION
**Pull request by jkwmoore**
Should close - https://github.com/hpc-social/jobs/issues/21

N.b. if the automation is going to process my new form entry this PR can probably be discarded.

### CODE REVIEW

**Comment by vsoch** [comment]
The easiest thing to try is to delete the job from our sheet, and then you can add a new entry. Let me know if you'd like me to proceed.

**Comment by jkwmoore** [comment]
As I've already submit the new listing to the form, deleting this seems wise.

I'll amend this PR now.

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
Just so you know, there is a Google form that backs this entire thing, so we can delete here for an immediate fix, but the larger fix is deleting from that Google Sheet (which I've done just now). Hopefully that will remove the job entirely.

**Comment by jkwmoore** [comment]
Many thanks!

**Pull request merged**
