### PR TITLE
Update jobs.yaml

### PR DESCRIPTION
**Pull request by patrickb314**
Current open position at the University of New Mexico

### CODE REVIEW

**Comment by vsoch** [comment]
hey @patrickb314 ! Any reason you didn't add this via our automated web form?

https://hpc.social/jobs/about/

You can do it from there, or the linked form. It will ensure we have the data in the yaml here plus the Google form (that the file updates from),

**Comment by patrickb314** [comment]
No particular reason, no. The link on hpc.social/jobs listed submitting a pull request as the first option, and the CS geek in me tends to prefer that to filling out google forms. If it makes sense, I'm happy to resubmit through the google form, however.

**Comment by vsoch** [comment]
I'm happy to add it here as a testing case - if we do see it disappear (I don't think it should) then we would need to go back and submit via the form. Let's merge and check tomorrow and see what happens!

**Review by vsoch — APPROVED** [review]

**Comment by patrickb314** [comment]
Thanks. :)

**Pull request merged**
